### ISSUE TITLE
license

### ISSUE THREAD

**Issue by danielecook** [dalcacer/pycodebox#1]
Hi - I'd like the use the parser you wrote. Happy to attribute the work. Do you have a license in mind?

Thanks,
Dan

**Comment by dalcacer** [comment]
Hi,
since I've stalled the development the source is free to use, i guess.
If licensing is an issue, I would employ the BSD or Apache License this afternoon.

Though, keep in mind that this source is considered to be a sketch.....

Kind regards
Dorian

**Comment by danielecook** [comment]
Thanks dalcacer. I am heavily modifying the code, but I will attribute the work. Have a good day.
